WArslett\TweetSync\Model\TwitterUser:
  type: entity
  repositoryClass: WArslett\TweetSync\ORM\Doctrine\TwitterUserRepository
  table: twitter__users
  id:
    id:
      type: string
  fields:
    screenName:
      type: string